### ISSUE TITLE
BTT Smart Sensor v2 Constantly triggering Switch Sensor

### ISSUE THREAD

**Issue by deadpickle** [bigtreetech/smart-filament-detection-module#55]
I'm running the BTT smart Sensor v2 on a Voron 2.4 with klipper. When I print things seem to work correctly until some point where the switch sensor gets triggered. When I heat the hotend and extrude, without touching anything, the filament extrudes just fine, and I start the print. I then enter a spiral where the print will go for a time but then the switch sensor will trigger, stop, extrudes fine, and repeat. Is then sensor bad? Have I missed something?

**Comment by Zephino** [comment]
change the detection_length to 3.88 

````
[filament_switch_sensor switch_sensor]
switch_pin: ^PA0
pause_on_runout: False
runout_gcode:
  PAUSE # [pause_resume] is required in printer.cfg
  M117 Filament switch runout
insert_gcode:
  M117 Filament switch inserted

[filament_motion_sensor encoder_sensor]
switch_pin: ^PC2
#detection_length: 2.88         #Stock
detection_length: 3.88          #Bappi
extruder: extruder
pause_on_runout: False
runout_gcode:
  PAUSE # [pause_resume] is required in printer.cfg
  M117 Filament encoder runout
insert_gcode:
  M117 Filament encoder inserted
````

**Comment by deadpickle** [comment]
This is for the encoder not the switch. I am still having this issue on and off
